name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  library:
    runs-on: ${{ matrix.host.image }}
    strategy:
      # Cancel all in-progress and queued jobs in the matrix if any job in the matrix fails
      fail-fast: true

      # matrix docs: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
      matrix:
        build_type: [Debug, RelWithDebInfo, Release, MinSizeRel]
        # image states
        # windows-2022: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
        # macos-14:     https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        host:
          # cl configurations
          #- { cpp_compiler: cl,         c_compiler: cl,       image: windows-2022, generator: Visual Studio 17 2022, vcpkg_triplet: x64-windows       }
          # clang++ configurations
          - { cpp_compiler: clang++,    c_compiler: clang,    image: macos-14,     generator: Unix Makefiles,        vcpkg_triplet: arm64-osx         } # GHA docs say this is version 15.0.0
    
    env:
      VCPKG_ROOT: ${{ github.workspace }}/code/deps/vcpkg
      VCPKG_BINARY_CACHE: ${{ github.workspace }}/.vcpkg_binary_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/.vcpkg_binary_cache,readwrite
      VCPKG_FEATURE_FLAGS: manifests,binarycaching

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Compute vcpkg SHA
        shell: bash
        run: echo "VCPKG_SHA=$(git -C code/deps/vcpkg rev-parse HEAD)" >> "$GITHUB_ENV"

      - name: Cache vcpkg downloads
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_ROOT }}/downloads
          key: vcpkgdl-${{ matrix.host.image }}-vcpkg:${{ env.VCPKG_SHA }}-manifest:${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: |
            vcpkgdl-${{ matrix.host.image }}-vcpkg:${{ env.VCPKG_SHA }}

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_BINARY_CACHE }}
          key: >
            vcpkgbin-${{ matrix.host.image }}-${{ matrix.build_type }}
            -triplet:${{ matrix.host.vcpkg_triplet }}
            -vcpkg:${{ env.VCPKG_SHA }}
            -manifest:${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-${{ matrix.host.image }}-${{ matrix.build_type }}-${{ matrix.host.cpp_compiler }}-${{ matrix.host.vcpkg_triplet }}
          max-size: 500M

      - name: bootstrap vcpkg (windows)
        if: runner.os == 'Windows'
        run: ${{ github.workspace }}\code\deps\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      - name: bootstrap vcpkg (mac)
        if: runner.os != 'Windows'
        run: ${{ github.workspace }}/code/deps/vcpkg/bootstrap-vcpkg.sh -disableMetrics

      # Use this to set up an open ssh debugging session with CI
      # - name: Setup ssh session
      #   uses: lhotari/action-upterm@v1

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "deps-dir=${{ github.workspace }}/code/deps" >> "$GITHUB_OUTPUT"
          echo "src-dir=${{ github.workspace }}/code/src" >> "$GITHUB_OUTPUT"
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake
          -G "${{ matrix.host.generator }}"
          -S ${{ github.workspace }}
          -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_TOOLCHAIN_FILE=${{ steps.strings.outputs.deps-dir }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.host.vcpkg_triplet }}
          -DCMAKE_CXX_COMPILER=${{ matrix.host.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.host.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest --build-config ${{ matrix.build_type }} --output-on-failure --no-tests=error